main: xyz.tangledwires.eventhandlertesting.EventHandlerTestingMain
name: EventHandlerTesting
author: xWires
version: 1.0
api-version: 1.20
commands:
  eventhandlertesting:
    description: Used to manage the EventHandlerTesting Plugin
    usage: /eventhandlertesting reload
    permission: eventhandlertesting.reload
    permission-message: You don't have permission to use this command.